eureka:
  client:
    service-url:
      defaultZone: http://eureka:password@localhost:8761/eureka
logging:
  level:
    root: INFO
    org.springframework.cloud.gateway.route.RouteDefinitionLocator: INFO
    org.springframework.cloud.gateway: TRACE
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        ## Operation Service Route
        - id: operation-service
          uri: lb://operation-service
          predicates:
            - Path=/api/operations/**,/api/operation-names/**,/api/operation-clients/**
        ## Discovery Service Route
        - id: discovery-service
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/web
          filters:
            - SetPath=/
        ## Discovery Service Static Resource Route
        - id: discovery-service-static
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/**
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/spring-boot-microservices-realm

management:
  tracing:
    sampling:
      probability: 1.0